server:
  port: 8080
  appCredentials:
    rootusername: root
    rootpassword: root
    Niel: niel
    interval: 5

ocpp:
  enabled: true
  heartbeatInterval: 300
  connectionTimeout: 60

devices:
  solar:
    - type: SMA
      name: sunnny-boy-4
      host: 192.168.129.15
    - type: SMA
      name: sunnny-boy-5
      host: 192.168.129.16
  grid:
    - type: HomeEnergy-P1
      gridType: 3Phase-230V
      host: 192.168.129.5
  heatPump:
    - type: daikin-homehub
      host: 192.168.129.131
  charger:
    - type: webbasto-unite-modbus
      host: 192.168.129.109
      chargingCurrent:
        min: 6.0
        max: 32.0

energyManager:
  config:
    P1meter: 192.168.129.5
    webasto: 192.168.129.109
    daikinHomeHub: 192.168.129.131
    mincurrent: 6.0
    maxcurrent: 32.0
